AsyncInn/AsyncInn/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AsyncInn.Models
{
    public class Hotel
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Hotel Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "City")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        public string Phone { get; set; }

        public int RoomCount { get; set; }

        //Navigation Properties

        public ICollection<HotelRoom> HotelRoom { get; set; }

    }
}

AsyncInn/AsyncInn/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AsyncInn.Data;
using AsyncInn.Models;
using AsyncInn.Models.Interfaces;

namespace AsyncInn.Controllers
{
    public class HotelsController : Controller
    {
        private readonly IHotelManager _context;
        private readonly AsyncInnDbContext _hotels;

        public HotelsController(IHotelManager context, AsyncInnDbContext hotels)
        {
            _context = context;
            _hotels = hotels;
        }

        // GET: Hotels
        /// <summary>
        /// Get all hotels
        /// </summary>
        /// <param name="searchString"></param>
        /// <returns>hotel view</returns>
        public async Task<IActionResult> Index(string searchString)
        {
            // var hotels = from h in _hotels.Hotels
            //  select h;
            var hotelcount = await _hotels.Hotels.ToListAsync();
            foreach (var i in hotelcount)
            {
                i.RoomCount = _hotels.HotelRooms.Where(room => room.HotelID == i.ID).Count();
            }

            
            if (!String.IsNullOrEmpty(searchString))    
            {
                var hotels = _hotels.Hotels.Where(htl => htl.Name.Contains(searchString));
                return View(hotels);
            }
            return View(hotelcount);
        }

        // GET: Hotels/Details/5
        /// <summary>
        /// show details of a hotel
        /// </summary>
        /// <param name="id"></param>
        /// <returns>detail view</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.GetHotel(id);
                
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // GET: Hotels/Create
        /// <summary>
        /// Create a hotel
        /// </summary>
        /// <returns>create view</returns>
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        /// <summary>
        /// Posts search results
        /// </summary>
        /// <param name="searchString"></param>
        /// <returns>index view</returns>
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>
        /// Show the details of new hotel
        /// </summary>
        /// <param name="id"></param>
        /// <param name="hotel"></param>
        /// <returns>index view</returns>
        public async Task<IActionResult> Create([Bind("ID,Name,Address,Phone")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                await _context.CreateHotel(hotel);
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        // GET: Hotels/Edit/5
        /// <summary>
        /// Shows details of a hotel for editing
        /// </summary>
        /// <param name="id"></param>
        /// <returns>hotel view</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.GetHotel(id);
            if (hotel == null)
            {
                return NotFound();
            }
            return View(hotel);
        }

   

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /// <summary>
        /// Display details of an hotel that were edited
        /// </summary>
        /// <param name="id"></param>
        /// <param name="hotel"></param>
        /// <returns>amenity view</returns>
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Address,Phone")] Hotel hotel)
        {
            if (id != hotel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.UpdateHotel(hotel);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        /// <summary>
        /// Show hotel to be deleted
        /// </summary>
        /// <param name="id"></param>
        /// <returns>delete view</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.GetHotel(id);
                
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        /// <summary>
        /// Shows hotel to be deleted
        /// </summary>
        /// <param name="id"></param>
        /// <returns>delete view page</returns>
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            await _context.DeleteHotel(id);
            return RedirectToAction(nameof(Index));
        }

        private bool HotelExists(int id)
        {
            return _context.HotelExists(id);
        }
    }
}

AsyncInn/AsyncInn/Views/Hotels/Create.cshtml
@model AsyncInn.Models.Hotel

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Create</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AsyncInn/AsyncInn/Views/Hotels/Delete.cshtml
@model AsyncInn.Models.Hotel

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AsyncInn/AsyncInn/Views/Hotels/Details.cshtml
@model AsyncInn.Models.Hotel

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Details</h1>

<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AsyncInn/AsyncInn/Views/Hotels/Edit.cshtml
@model AsyncInn.Models.Hotel

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";

}

<h1>Edit</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AsyncInn/AsyncInn/Views/Hotels/Index.cshtml
@model IEnumerable<AsyncInn.Models.Hotel>

@{
    ViewData["Title"] = "Title";
    Layout = "_Layout";
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Hotels" asp-action="Index" method="get">
    <p>
        Search by Name: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<p>Total Hotels: @Model.Count()</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoomCount)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomCount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>